### ISSUE TITLE
Test architecture

### ISSUE THREAD

**Issue by georgkrause** [metabrainz/listenbrainz-matching-tools#10]
Currently the project uses python native `unittest` to run tests. I do see some issues with the current implementation and suggest to migrate to pytest. There are several reasons:

* Other metabrainz projects seem to use pytest, so it helps using the same tech everywhere
* We need parametrized tests. This isn't natively supported by unittest
  * Our current workaround is to manually build suits to pass test data as parameter
  * This way we disable automatic discovery, which is problematic because new tests need to be manually disabled (might result in false positives!)
  * Another workaround would be using a unittest extension, and if we do this we can use pytest right away

**Comment by georgkrause** [comment]
Pytest also has more capabilities when it comes to reporting

**Comment by ShashankSrivastava2002** [comment]
hello @georgkrause  sir. Sir I want to work on this issue. Can you assign me this. also want to talk to you about the problem in way more detail.

**Comment by georgkrause** [comment]
I think @mayhem already solved this in #11  and this can be closed
